import { Web3Button } from "@web3modal/react";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useState } from "react";

import { CreateVault } from "~/components/createvault";
import { SignIn } from "~/components/signin";
import { ViewProfile } from "~/components/viewprofile";
import { api } from "~/utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <Web3Button />
        <title>Wave Protocol</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="min-h-screen bg-[#DDDDDD]">
        <main className="mx-auto flex w-full max-w-md">
          <div className="">
            <div className="mb-5" />
            <SignIn />
            <div className="mb-5" />
            <CreateVault />
            <div className="mb-5" />
            <ViewProfile />
            <div className="mb-5" />
            {/* <p className="">
            {hello.data ? hello.data.greeting : "Loading tRPC query..."}
          </p> */}
          </div>
        </main>
      </div>
    </>
  );
};

export default Home;
