import { type NextPage } from "next";
import Head from "next/head";

import { BottomNav } from "~/components/bottomnav";
import { ConnectionsList } from "~/components/connectionslist";

const Search: NextPage = () => {
  const mutualConnections = [
    { name: "Jeff", handle: "@jeff", avatar: "https://i.pravatar.cc/300" },
    { name: "Sarah", handle: "@sarah", avatar: "https://i.pravatar.cc/301" },
    { name: "Dave", handle: "@dave", avatar: "https://i.pravatar.cc/302" },
    {
      name: "Tara Reeves",
      handle: "@tara",
      avatar: "https://i.pravatar.cc/303",
    },
    {
      name: "Michael",
      handle: "@michael",
      avatar: "https://i.pravatar.cc/304",
    },
    { name: "Alicia", handle: "@alicia", avatar: "https://i.pravatar.cc/305" },
    { name: "Samantha", handle: "@sam", avatar: "https://i.pravatar.cc/306" },
    { name: "Wade", handle: "@wade", avatar: "https://i.pravatar.cc/307" },
    { name: "Oscar", handle: "@oscar", avatar: "https://i.pravatar.cc/308" },
    { name: "Jimmy", handle: "@jimmy", avatar: "https://i.pravatar.cc/309" },
    {
      name: "Victoria",
      handle: "@victoria",
      avatar: "https://i.pravatar.cc/310",
    },
    { name: "Danny", handle: "@danny", avatar: "https://i.pravatar.cc/311" },
    { name: "Celine", handle: "@celine", avatar: "https://i.pravatar.cc/312" },
    { name: "Wendy", handle: "@wendy", avatar: "https://i.pravatar.cc/313" },
    { name: "Travis", handle: "@travis", avatar: "https://i.pravatar.cc/314" },
    {
      name: "Melinda",
      handle: "@melinda",
      avatar: "https://i.pravatar.cc/315",
    },
    { name: "Shawn", handle: "@shawn", avatar: "https://i.pravatar.cc/316" },
    { name: "Olivia", handle: "@olivia", avatar: "https://i.pravatar.cc/317" },
    { name: "Gavin", handle: "@gavin", avatar: "https://i.pravatar.cc/318" },
    { name: "Monica", handle: "@monica", avatar: "https://i.pravatar.cc/319" },
  ];
  return (
    <>
      <Head>
        <title>Wave Protocol</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="min-h-screen bg-[#DDDDDD]">
        <main className="mx-auto flex w-full max-w-md">
          <div className="">
            <ConnectionsList connections={mutualConnections} />
            <BottomNav />
            <div className="mb-20" />
          </div>
        </main>
      </div>
    </>
  );
};

export default Search;
